" load settings file before everything else
runtime! settings.vim

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin()

if executable('fzf')
    " add path to system fzf before installing vim plugin
    Plug '/usr/bin/'
else
    Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
endif
Plug 'junegunn/fzf.vim'
" Client for Language server protocol and languge specific linters/fixers
Plug 'dense-analysis/ale'
" Git tooling inside vim
Plug 'tpope/vim-fugitive'
Plug 'lifepillar/vim-gruvbox8'
" fold blocks of code in python
" Plug 'tmhedberg/SimpylFold'
" autogenerate docstrings for python functions/classes
Plug 'heavenshell/vim-pydocstring', { 'do': 'make install', 'for': 'python' }
Plug 'vim-python/python-syntax'
Plug 'bfrg/vim-cpp-modern'
Plug 'chrisbra/Colorizer'
Plug 'lervag/vimtex'
" Syntax highlighting for i3wm config file.
Plug 'mboughaba/i3config.vim'
Plug 'vifm/vifm.vim'
" Preview markdown files
Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }, 'for': ['markdown', 'vim-plug']}
" syntax highlighting and filetype plugins for Markdown
Plug 'tpope/vim-markdown'
" code snippet engine
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
call plug#end()

" map <Leader>h to command thats turns off highlighting
nnoremap <Leader>n :nohl<CR>
" exit insert mode using ii
inoremap jj <C-c>
" buffer navigation mappings
nnoremap <Leader>b :buffers<CR>
nnoremap <Leader>h :history<CR>
nnoremap <Leader>j :bprevious<CR>
nnoremap <Leader>k :bnext<CR>
nnoremap <Leader>c :bd<CR>
nnoremap <Leader>f :Vifm<CR>
nnoremap <Leader>s :Snippets<CR>
" Navigate quickfix list
nnoremap <Leader>co :copen<CR>
nnoremap <Leader>cc :cclose<CR>
nnoremap <Leader>cn :cnext<CR>
nnoremap <Leader>cp :cprev<CR>
" disable use of arrow keys in all modes
noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>
" use tab to step through completion choices instead when pop-menu is shown.
inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
" use shift-tab to step backwards through completion choices
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
" use enter to to close the completion pop-up when not wanted
inoremap <expr> <cr>    pumvisible() ? "\<C-y>" : "\<cr>"
" map to generate python docstrings
"nmap <silent> <Leader>pd :Pydocstring<CR>
nmap <silent> <Leader>pp <Plug>(pydocstring)

nnoremap <Leader>gs :G<CR>

" Gruvbox color scheme
" ====================
let g:gruvbox_filetype_hi_groups=1
let g:gruvbox_plugin_hi_groups=1
colorscheme gruvbox8_soft

" Color Highlighter
" =================
let g:colorizer_auto_color = 1
let g:colorizer_auto_filetype='css,html'
let g:colorizer_colornames = 0

" vim Markdown config
" ===================
let g:markdown_fenced_languages = ['html', 'python', 'bash=sh', 'go', 'javascript', 'c']

" vimtex config
" =============
let g:vimtex_view_method = 'zathura'
let g:vimtex_compiler_method = 'latexmk'
let maplocalleader = "<space>"

" snippets config
" ===============
let g:UltiSnipsExpandTrigger=";<tab>"
