#!/bin/sh
# vim: ft=sh

while read file
do
        case "$1" in
        "C-d")
                trash-put "$file" ;;
        "C-r")
                convert -rotate 90 "$file" "$file" ;;
        "C-c")
                echo -n "$file" | xclip -selection clipboard ;;
        "C-w")
                NUM_MONITORS=$(xrandr --listmonitors | grep Monitors | awk -F': ' '{print $2}')
                for (( i = 0; i < ${NUM_MONITORS}; i++ )); do
                    nitrogen --save --set-scaled --head=${i} "$file"
                done
        esac
done
